//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dblogEntities : DbContext
    {
        public dblogEntities()
            : base("name=dblogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Clientes> Tbl_Clientes { get; set; }
        public virtual DbSet<Tbl_Entregas> Tbl_Entregas { get; set; }
        public virtual DbSet<Tbl_Motoboys> Tbl_Motoboys { get; set; }
    
        public virtual ObjectResult<uspConsultarEntregas_Result> uspConsultarEntregas(Nullable<int> iNintIDMotoboy)
        {
            var iNintIDMotoboyParameter = iNintIDMotoboy.HasValue ?
                new ObjectParameter("INintIDMotoboy", iNintIDMotoboy) :
                new ObjectParameter("INintIDMotoboy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspConsultarEntregas_Result>("uspConsultarEntregas", iNintIDMotoboyParameter);
        }
    }
}
