//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Clientes()
        {
            this.Tbl_Entregas = new HashSet<Tbl_Entregas>();
            this.Tbl_Motoboys = new HashSet<Tbl_Motoboys>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nome { get; set; }
        public string email { get; set; }
        public string Telefone { get; set; }
        public string Responsavel { get; set; }
        public string Area_Unidade { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Entregas> Tbl_Entregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Motoboys> Tbl_Motoboys { get; set; }
    }
}
