//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Entregas
    {
        public int ID_Entrega { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_Motoboy { get; set; }
        public string Nome_Destinatario { get; set; }
        public string Endereco { get; set; }
        public string Ponto_Ref { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Cod_Encomenda { get; set; }
        public Nullable<System.DateTime> Data_Encomenda { get; set; }
        public Nullable<System.DateTime> Data_Entrega { get; set; }
        public string Telefone { get; set; }
        public string Observacoes { get; set; }
        public Nullable<bool> Entregue { get; set; }
        public string Status_Entrega { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Motoboys Tbl_Motoboys { get; set; }
    }
}
