//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Motoboys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Motoboys()
        {
            this.Tbl_Entregas = new HashSet<Tbl_Entregas>();
        }
    
        public int ID_Motoboy { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Nome { get; set; }
        public string email { get; set; }
        public string Telefone { get; set; }
        public string WhatsApp { get; set; }
        public string Veiculo { get; set; }
        public string Modelo { get; set; }
        public string Placa { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public string GeoLatitude { get; set; }
        public string GeoLongitude { get; set; }
        public string GeoAccuracy { get; set; }
        public Nullable<System.DateTime> GeoDataLoc { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Entregas> Tbl_Entregas { get; set; }
    }
}
